tools/php/.env.sample, tools/php/.gitignore, tools/php/README.md, tools/php/bomber.php, tools/php/composer.json
* Скрипт для генерации ошибок в php
* в качестве handler - https://github.com/codex-team/hawk.php
=> Bomber for php errors

.gitignore, package.json, tools/nodejs/.env.sample, tools/nodejs/bomber.js, tools/php/.env.sample, tools/php/bomber.php, tools/php/composer.json, workers/nodejs/index.js, yarn.lock
+ 10 ошибок для nodejs(все возможные), [доки по ошибкам nodejs](https://nodejs.org/api/errors.html)
+ 10 ошибок для php(не все возможные), [доки по ошибкам php](http://php.net/manual/ru/class.exception.php)
=> Рандомизация ошибок в bomber.js и bomber.php

lib/db/controller.ts, runner.ts, workers/javascript/src/index.ts, workers/source-maps/src/index.ts, workers/source-maps/tests/index.test.ts, workers/source-maps/types/source-maps-record.d.ts
+ fixes in runner.ts error handling
+ fix of missed db name in env
+ fix maps overriding by upsert: now it is 2 separated request (select and insert/update)
+ JS worker: downloading source map content from grid fs
=> Using mongo gridfs for storing source maps

workers/grouper/src/index.ts
=> Hotfix: disable single event addons

lib/db/controller.ts, lib/workerErrors.ts, workers/grouper/src/index.ts, workers/javascript/src/index.ts, workers/php/index.js, workers/source-maps/src/index.ts
DatabaseError:
DatabaseReadWriteError (non-critical)
DatabaseConnectionError (critical)
=> non-critical database errors

workers/archiver/src/index.ts
=> replaced deleteMany with bult remove operation

.github/workflows/main.yml, workers/nodejs/types/nodejs-event-worker-task.d.ts
пушим на докерхаб, чтобы избавиться от приватного registry
=> change workflow for pushing to dockerhub

workers/archiver/.env.sample, workers/archiver/src/index.ts
=> add server name to Hawk Archiver message

.github/workflows/main.yml
=> Enable stage deploy of the newest version

.github/workflows/update-monorepository.yml
GitHub Action to provide auto-merge of submodule in mono-repository
=> Add autopush to mono via GitHub Actions

workers/grouper/src/index.ts
=> Catch end process MongoDB duplication error

package.json, workers/paymaster/src/index.ts, yarn.lock
Adds env checker, updates codex-accounting-sdk version.
=> [Feaure] Add env variables checking

.env.test, workers/paymaster/.env.sample, workers/paymaster/package.json, workers/paymaster/src/index.ts, workers/paymaster/tests/index.test.ts, yarn.lock
Paymaster worker now will send reports like this:
closes #157
=> [Feature] Reports for paymaster worker

.github/workflows/main.yml, stage.Dockerfile
Move github build action to the fresh version (v2)
Add new migration tag which will consist of the all essential files for yarn migrate:up
=> Build migrate

.eslintrc.js, package.json, yarn.lock
Upgrades config to the latest version.
=> [Upgrade] EsLint config CodeX

workers/paymaster/.env.sample, workers/paymaster/README.md, workers/paymaster/src/index.ts, workers/paymaster/tests/index.test.ts, workers/paymaster/types/paymaster-worker-events.ts, yarn.lock
Checks workspace for an actual subscription. If it hasn't, the paymaster will block the workspace.
Request without actual tests for paymaster. Without sending an email about block to a workspace team.
Checks describe in #185.
=> [Feature] Paymaster checks subscription

.eslintrc.js, lib/logger.ts, lib/utils/string.ts, lib/worker.ts, package.json, workers/grouper/src/index.ts, workers/grouper/tests/index.test.ts, workers/javascript/src/index.ts, workers/limiter/README.md, workers/limiter/src/index.ts, workers/limiter/src/redisHelper.ts, workers/limiter/tests/index.test.ts, workers/limiter/types/eventTypes.ts, workers/limiter/types/index.ts, workers/limiter/types/reportData.ts, workers/paymaster/.env.sample, workers/paymaster/README.md, workers/paymaster/src/index.ts, workers/paymaster/tests/index.test.ts, workers/paymaster/types/paymaster-worker-events.ts, yarn.lock
Merges `master` branch to `prod` and deploys on production.
=> [Deploy] Deploy master branch to production

.env.sample, runner.ts
* optimize push time 1s -> 10s
* unhardcode push time -> .env
* `push` -> `pushAdd`
=> Metrics optimization

workers/paymaster/src/index.ts
Adds task for Email sender worker about blocking workspace.
Closes #185.
=> [Feature] Send email message about blocking workspace

package.json, workers/grouper/package.json, workers/grouper/src/data-filter.ts, workers/grouper/src/index.ts, workers/grouper/tests/data-filter.test.ts, workers/grouper/tests/index.test.ts, yarn.lock
Grouper now can modify event payload:
1. Filter Bank Card number from any values of `context` and `addons`
2. Filter values which keys are in the predefined list of sensitive data keys.
=> feature(grouper): sensitive data filtering

lib/worker.ts
Refactor error catching to switch-case.
Now worker sends messages with NonCriticalError to stash.
Closes #123
=> [Refactor] Error catching in worker.ts

package.json, workers/grouper/.env.sample, workers/grouper/package.json, workers/grouper/src/index.ts, workers/grouper/src/redisHelper.ts, workers/grouper/tests/index.test.ts, workers/limiter/package.json, workers/limiter/tests/index.test.ts, yarn.lock
at the moment, affected users are counted incorrectly when processing the same event in parallel with several instances
=> [Fix] Affected users counting

lib/worker.ts, package.json, workers/archiver/package.json, workers/grouper/.env.sample, workers/grouper/package.json, workers/grouper/src/data-filter.ts, workers/grouper/src/index.ts, workers/grouper/src/redisHelper.ts, workers/grouper/tests/data-filter.test.ts, workers/grouper/tests/index.test.ts, workers/limiter/package.json, workers/limiter/tests/index.test.ts, workers/paymaster/package.json, workers/telegram/package.json, yarn.lock
— sensitive data filtering
— dependencies update
— error catching fixes in abstract worker
— fix affected users counting
=> Deploy prod

.github/workflows/nodejs.yml, jest-mongodb-config.js, lib/utils.js, package.json, workers/grouper/package.json, workers/grouper/src/data-filter.ts, yarn.lock
- fix `DataFilter` bug ([Hawk event](https://beta.hawk.so/project/5ee7a80de6ce2b651831f26e/event/60c37bf397b9af2a6607931e/overview))
- add `node_modules` caching for Unit tests GH Action
- fix `deepDiff` bug when both source and targets are empty strings
- update mongodb memory server version
- run tests sequentially in order to prevent race conditions
=> Fix DataFilter iterating all props

workers/grouper/src/index.ts
https://beta.hawk.so/project/5ee7a80de6ce2b651831f26e/event/60bf80b11669c4a6a96a83a4/60cc7d599e6987d3a55535ca/overview
=> Fix throwing error in catch clause

workers/limiter/src/index.ts, workers/limiter/tests/index.test.ts
=> Add check for isBlocked field

workers/email/src/provider.ts, workers/email/src/templates/emails/block-workspace/html.twig, workers/email/src/templates/emails/block-workspace/text.twig, workers/email/src/templates/emails/days-limit-almost-reached/html.twig, workers/email/src/templates/emails/days-limit-almost-reached/text.twig, workers/email/src/templates/emails/events-limit-almost-reached/html.twig, workers/email/src/templates/emails/events-limit-almost-reached/subject.twig, workers/email/src/templates/emails/events-limit-almost-reached/text.twig, workers/email/src/templates/emails/payment-failed/html.twig, workers/email/src/templates/emails/payment-success/html.twig, workers/email/src/templates/emails/payment-success/text.twig, workers/email/src/templates/names.ts, workers/limiter/README.md, workers/limiter/src/index.ts, workers/limiter/tests/index.test.ts, workers/limiter/types/reportData.ts, workers/paymaster/README.md, workers/paymaster/src/index.ts, workers/sender/src/index.ts, workers/sender/src/utils/time.ts, workers/sender/types/sender-task/events-limit-almost-reached.ts, workers/sender/types/sender-task/index.ts, workers/sender/types/template-variables/events-limit-almost-reached.ts, workers/sender/types/template-variables/index.ts, yarn.lock
block workspace and send a notification
also
resolves #245
todo
- update cron config in automation codex-team/hawk.automation#93
=> Limiter "event limit has been reached" email

workers/limiter/src/index.ts, workers/paymaster/src/index.ts
=> fix: limiter: remove notifications

workers/release/src/index.ts
Due to changes in the collector https://github.com/codex-team/hawk.collector/pull/93
=> Made commits optional

dev.Dockerfile, workers/grouper/package.json, workers/grouper/src/index.ts, workers/grouper/tests/index.test.ts, workers/release/src/index.ts, yarn.lock
This feature will allow to group similar events like:
1. Get last N unique events, **and cache them**
2. Compute the Levenshtein distance
3. Find those which distance less than 35% of the string length
=> feat(grouper): grouping by Levenshtein distance 👺

lib/worker.ts
=> fix(lib/worker): check if the cache is prepared before flushAll

workers/email/scripts/emailOverviewForm.twig, workers/email/src/templates/components/backtrace.twig, workers/email/src/templates/components/event-info.twig, workers/email/src/templates/components/event.twig, workers/email/src/templates/components/filename.twig, workers/email/src/templates/components/layout.twig, workers/email/src/templates/emails/event/html.twig, workers/email/src/templates/emails/several-events/html.twig, workers/email/src/templates/extensions.ts
Fix artifacts in emails
Resolves #288
=> Fix backtrace styles

workers/email/src/templates/emails/password-reset/html.twig, workers/email/src/templates/emails/password-reset/text.twig
=> Fixed text and link

workers/email/src/templates/emails/events-limit-almost-reached/html.twig, workers/email/src/templates/emails/events-limit-almost-reached/subject.twig
So the project is free. Changes were made on the site, it was necessary to change the description in the letter
=> Changed the content of the limit events email

Dockerfile, package.json, yarn.lock
They were caused by @shelf/jest-mongodb update
=> fix(build): build errors fixed

.github/workflows/build-and-push-docker-image.yml, .github/workflows/check-build.yaml, package.json, yarn.lock
=> fix(build): restore correct yarn.lock

.github/workflows/nodejs.yml, workers/notifier/src/index.ts
- Add verbose level logs for notifier worker
- Fix bug with skipping list of rules if one of them is disabled / whatToReceive === `ONLY_NEW`
- Update `actions/cache` in eslint workflow from 2 to 3
=> logs(notifier): add verbose level logs

workers/javascript/src/index.ts, workers/release/src/index.ts
=> Chore(logs): add verbose level logs for javascript and release workers

lib/worker.ts, workers/email/src/templates/extensions.ts, workers/grouper/src/index.ts, workers/grouper/src/redisHelper.ts, workers/grouper/tests/index.test.ts, workers/javascript/src/index.ts, workers/javascript/tests/index.test.ts, workers/notifier/src/index.ts, workers/notifier/src/redisHelper.ts, workers/notifier/tests/worker.test.ts, workers/release/src/index.ts
- Improve javascript function name parsing
- Add raw event repetition saving for debug purposes
=> Imp(javascript) javascript function name parsing

package.json, workers/archiver/src/index.ts, workers/archiver/tests/index.test.ts, workers/archiver/tests/releases.mock.ts
now archiver worker archived all events except last three, in case, when we can have several releases a day that can cause unexpected behaviour
Rewrite archiver to archive releases that are more than one month old
=> Imp(archiver): releases archiving

convertors/move-timestamp-out-of-payload.js, workers/grouper/src/index.ts, workers/grouper/tests/index.test.ts
Now grouping by Levenstein is commented
Events with resembling titles are treated as different ones
=> chore(): disable grouping by levenstein
