.env.sample
.travis.yml
README.md
lib/worker.js
lib/worker.test.js
lib/workerFailover.test.js
tools/nodejs/bomber.js
workers/nodejs/index.js
workers/nodejs/runner.js

В базовый класс `Worker` были добавлены методы:
- `requeue` - возвращает сообщение в ту очередь, откуда оно пришло
- `requeueAll` - тоже самое, только для всех сообщений в обработке
- `sendToStash` - отправка сообщения в "стеш", где оно будет обрабатываться в дальнейшем
При возникновении `NonCriticalError` сообщение отправляется в стеш
При возникновении `CriticalError` (воркер падает или завершается) сообщение идет обратно в очередь, т.к. его обработка была прервана
Эти ошибки можно кидать в `Worker.handle`, чтобы отправить сообщение туда, куда нужно
При вызове `Worker.finish()` воркер отправляет все сообщения обратно в очередь. Этот метод вызывается при падении воркера
Closes #17

Requeueing and stash

---

lib/workerNames.js

The current version of file contains a broken worker names dictionary with extra space in the path.
So in master, workers can not add tasks to each other, because they can't get queue name.

Fix workers names dictionary

---

migrations/20201201100438-add-repetition-payload-timeout-index.js

This will reduce execution timings on hawk archive worker
```
repetitionsBulk.find({
'payload.timestamp': {
$lt: maxOldTimestamp,
},
}).remove();
```

Add migration to the repetitions collection on payload.timeout

---

lib/logger.ts
lib/worker.ts
workers/limiter/README.md
workers/limiter/src/index.ts
workers/limiter/src/redisHelper.ts
workers/limiter/tests/index.test.ts
workers/limiter/types/eventTypes.ts
workers/limiter/types/index.ts
workers/limiter/types/reportData.ts

Теперь можно отправить задачу вида
```
{
"type": "check-single-workspace",
"workspaceId":""
}
```
чтобы лимитер проверил воркспейс и заблокировал\разблокировал его

Check workspace event

---

lib/utils/string.ts
workers/javascript/src/index.ts

We want to prevent a memory leak from storing long source code lines:

fix(js): trim source code lines

---

workers/sender/src/index.ts
workers/sender/types/sender-task/blockWorkspace.ts
workers/sender/types/sender-task/index.ts
workers/sender/types/template-variables/blockWorkspace.ts
workers/sender/types/template-variables/index.ts

Adds types and logic for block workspace message to sender worker. For #185.

[Feature] Block workspace message in sender worker

---

workers/paymaster/src/index.ts
workers/paymaster/tests/index.test.ts

Paymaster doesn't work now because of this error. 
In case such an error occurs, the paymaster should notify us about it via the hawk, but not complete the process.

do not throw error if lastChargeDate is undefined

---

workers/archiver/src/index.ts
workers/archiver/src/types.ts

не был учтён кейс когда в релизах поле files не определено
Также заменил remove на delete тк remove deprecated

fix case when files field is undefined

---

workers/grouper/src/index.ts

When many similar events processed in parallel, check for `isFirstOccurence` returns falsy-false value since we have no db lock. So all second events are processed as the first one.
We have a special try-catch statement that handles this case by catching Mongo "duplicate error". This statement re-runs processing for a particular event. But looks like we've lost `return` there, so on each re-run increment was added anyway

fix(grouper): fix parallel events increment

---

.eslintignore
Dockerfile
package.json
tsconfig.json

This PR fixed build: 
https://github.com/codex-team/hawk.workers/actions/runs/12430488671

fix(build): do not build unnecessary js

---

runner.ts
workers/grouper/src/redisHelper.ts

It will help debugging workers failure

chore(logs): add logs and try catch blocks

---

workers/grouper/src/index.ts
workers/grouper/tests/index.test.ts

1. Removed incrementing affected users if user is not provided for the first event
2. Fixed test for daily, added test for event

fix: not increment affected users if user is not provided

---

workers/notifier/src/index.ts
workers/notifier/src/validator.ts
workers/notifier/tests/validator.test.ts
workers/sender/src/index.ts
workers/telegram/src/provider.ts

- Added verbose logs to notifier's rule validator (also small changes in errors thrown in validator)
- Update related validator tests
- Removed duplicated logic from notifier (double checking of `rule.isEnabled`)
- Added verbose log to sender worker (it would be extender by telegram / slack / email workers)
- Small style fix in telegram provider

Chore(notifications): added verbose logs for notification rules validation and sender

---

lib/utils/time.ts
workers/grouper/src/index.ts
workers/notifier/src/index.ts
workers/sender/src/index.ts

Now we are using `Time.MINUTE` constant as ttl for `NodeCache.set` time limit parameter
`Time.MINUTE` stores time in milliseconds, however `NodeCache.set` requires ttl in seconds
This is why cache is not updated for 1000 minutes ~ 17 hrs, so rules are updated from db with 17 hrs delay
Pass `Time.MINUTE / 1000` to pass ttl in seconds
- Notifier
- Grouper

fix(notifier): fix cache usage

---

workers/javascript/src/index.ts

- remove handle log because worker send this log by default
- moved from info level logs to verbose because info level displays objects like [ object: Object ]
- added more logs for some cases

Imp(javascript): improve logs

---

workers/javascript/src/index.ts

- Now if source-map lib returns method name - it would be set to the backtrace

imp(javascript): parse function name from backtrace

---

package.json
workers/javascript/src/index.ts
yarn.lock

Now source map consumer parses closest to the original location word as a function name
In most cases it works, but sometimes we can get variable name or function arg as a function name
Also class name are still minified
- Use babel parser to get functionContext of the original location
- Cover all cases with class methods, functions outside of the class and anonymous functions

Imp(javascript): babel source map parsing

---

workers/notifier/src/redisHelper.ts
workers/notifier/tests/redisHelper.test.ts

The problem is that we do not delete any of the inserted redis records (related to the notification rules)
this leads to memory leak
- Add ttl for every redis key, used for notification counters (ttl equals to the rule thresholdPeriod, when ttl passed, record will be deleted from the redis store)
- Cover expiration with tests

imp(notifier): add ttl for redis records

---

jest-mongodb-config.js
jest.config.js
jest.setup.mongo-repl-set.js
workers/release/src/index.ts
workers/release/tests/index.test.ts

test improved release saving on stage

Improve release saving

---

jest-mongodb-config.js
jest.config.js
jest.setup.mongo-repl-set.js
workers/release/src/index.ts
workers/release/tests/index.test.ts

Now, due to async db read/write methods we can have several records with same release string, but with different file lists
- Read and write to release table inside of one transaction
- Cover with tests

imp(release): source map saving in transaction to solve race condition issue

---

workers/release/src/index.ts

Try-catch does not work if we catching sync error, that is inside of unresolved promise, that's why we were getting error from `saveFile` method, however it is inside of try-catch.
- covered cases, that leaded to this error - empty `mapBodyString` leaded to error in `const readable = Readable.from([ file.content ]);`
- Now we are separating files with empty contents and do not save them

fix(releases): cover case with empty map body

---

lib/utils/hasValue.ts
workers/paymaster/src/index.ts
workers/paymaster/tests/index.test.ts

- Now if month passed for workspace with paidUntil set to several months in the future - paymaster will recharge the workspace

feat(paymaster): add paidUntil recharge logic

---

workers/email/src/templates/emails/event/html.twig
workers/email/tests/provider.test.ts
workers/sender/src/index.ts
workers/sender/types/template-variables/event.ts

Update unsubscribe link in event email

fix(emails): Update unsubscribe link

---

workers/grouper/src/index.ts
workers/grouper/tests/index.test.ts

- grouping patterns are stored in db in format 
```ts
export interface ProjectEventGroupingPatternsDBScheme {
/**
* If of the pattern
*/
_id: ObjectId;
/**
* String that represents regular expression pattern
*/
pattern: string;
}
```
but we are treating them as `string[]`. That leads to this type of errors:
```
2025-07-17T14:33:40.699Z error: Error while getting original event for pattern [object Object] 
```
- also this issue is invisible for tests because of incorrect grouping patterns mocking (they are mocked as `string[]` as well)
- Treat grouping patterns as described in `ProjectEventGroupingPatternsDBScheme` interface (as they actually stored)
- Fix mocks in tests

Fix(grouper): grouping patterns

---

workers/notifier/src/validator.ts

- Notifier excluding words validation works unexpectedly, it lowers event title but now lowers excluding word to check

imp(): improve notifier excluding words validation

---

workers/javascript/src/index.ts
workers/release/src/index.ts

- On some saves we had this kind of error related to the transactions
we've implemented transactions in this pr: (https://github.com/codex-team/hawk.workers/pull/390)
so now if some of the transaction is blocked (it will stop and then re-run after db lock will be removed) but in js we already mutated savedFile object (we used `delete file.content;` and it led to errors on transaction re-run)
- do not mutate original savedFiles object to avoid errors on transaction re-run

fix(): fix source-map saving

---

package.json
workers/grouper/src/index.ts
workers/grouper/tests/index.test.ts
yarn.lock

* Implemented a new method to check if an event is marked as ignored.
* Add task for NotifierWorker only if event is not ignored
Resolves #423

fix(grouper): skip notifications for muted errors
